name: Makefile CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Work around problem with installing some i386 packages (see https://github.com/actions/virtual-environments/issues/4589)
        run: sudo apt install -y --allow-downgrades libpcre2-8-0=10.34-7
      - name: Install dependencies
        run: ./bdeps.sh
      - name: Build
        run: make -j $(nproc)
      - name: Upload artifacts
        uses: actions/upload-artifact@v2.3.1
        with:
          path: |
            hook.dll
            withdll.exe
            mpris-server.dll
          if-no-files-found: error
